# Generated by Django 6.0.4 on 2026-04-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='poster_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
