# Generated by Django 6.0.4 on 2026-06-02 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_series_poster_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
